function objSet = CombineImages(OS1, OS2)

    objSet.labels = OS1.labels | OS2.labels;
	objSet.props = regionprops(logical(objSet.labels), ...
								'Area', ...
								'Eccentricity', ...
								'MajorAxisLength', ...
								'MinorAxisLength', ...
								'Perimeter', ...
								'Solidity', ...
								'ConvexArea', ...
                                'EquivDiameter', ...
                                'Centroid', ...
								'Orientation');
	objSet.labels = bwlabel(objSet.labels);
	
	for(i=1:size(objSet.props,1))
		objSet.props(i).label = i;
	end

end
